[build]
  publish = "public"
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.9"

# API routes - redirect to specific Netlify functions
[[redirects]]
  from = "/api/send-to-telegram"
  to = "/.netlify/functions/send-to-telegram"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-order-to-telegram"
  to = "/.netlify/functions/send-order-to-telegram"
  status = 200
  force = true

[[redirects]]
  from = "/api/test-telegram"
  to = "/.netlify/functions/test-telegram"
  status = 200
  force = true

[[redirects]]
  from = "/api/get-chat-id"
  to = "/.netlify/functions/get-chat-id"
  status = 200
  force = true

# Static files - serve from public directory
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 