[build]
  publish = "public"
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.9"

# API routes - redirect to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Static files - serve from public directory
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 